resource_group = "sasiRG"
location = "eastus"
vnet = "sasivnet"
cidr_block = "192.168.0.0/16"
vsub = "sasisubnet"
ip_address = "192.168.2.0/24"
nic = "sasi_nic"
ipconfig = "sasiip"
vm= "sasivm1"
size = "standard_f2"
vmuser_name = "sasiweb1"
user_password = "websasi@2022"
rights = "ReadWrite"
storage = "Standard_LRS"
micsft = "microsoftwindowsserver"
win = "windowsserver"
vmwin_versing = "2016-datacenter"

